- name: Install Frontend Server
  hosts: frontend-server
  become: yes
  roles:
    - teleport
    - docker
    - portainer-agent
    - role: github-runner
      vars:
        github_repo_url: "https://github.com/DevopsLPT"
        runner_token: "A4TCJZ6ZDBORXWVBZOCWSZLHVC7PS"   
        label: "shoeshop-frontend"
        